# Auto-generated by CI. Do not edit manually.
# Regenerate with:
#   git describe --tags --dirty --always > _version.txt
#   python -c "
#   import pathlib
#   v = pathlib.Path('_version.txt').read_text().strip()
#   pathlib.Path('_version.py').write_text(f'__version__ = {v!r}\n')
#   "
__version__ = "1.0.001"
